In [1]:
import pandas as pd

from process import tratamento_base

In [2]:
df_base = tratamento_base(2004,2024)

processing file 20041, mem consumption: 132
processing file 20042, mem consumption: 634692

processing file 20043, mem consumption: 1270628
processing file 20044, mem consumption: 1907268
processing file 20045, mem consumption: 2544420
processing file 20046, mem consumption: 3181732
processing file 20047, mem consumption: 3823940
processing file 20048, mem consumption: 4454852
processing file 20049, mem consumption: 5088804
processing file 200410, mem consumption: 5724228
processing file 200411, mem consumption: 6357028
processing file 200412, mem consumption: 6983396
processing file 20051, mem consumption: 7606180
processing file 20052, mem consumption: 8220868
processing file 20053, mem consumption: 8838756
processing file 20054, mem consumption: 9457796
processing file 20055, mem consumption: 10079332
processing file 20056, mem consumption: 10698180
processing file 20057, mem consumption: 11314756
processing file 20058, mem consumption: 11920804
processing file 20059, mem consumption: 12529476
processing file 200510, mem consumption: 13141924
processing file 200511, mem consumption: 13757476
processing file 200512, mem consumption: 14373860
processing file 20061, mem consumption: 14986596
processing file 20062, mem consumption: 15592580
processing file 20063, mem consumption: 16201988
processing file 20064, mem consumption: 16813860
processing file 20065, mem consumption: 17429700
processing file 20066, mem consumption: 18047364
processing file 20067, mem consumption: 18668516
processing file 20068, mem consumption: 19280740
processing file 20069, mem consumption: 19882628
processing file 200610, mem consumption: 20486148
processing file 200611, mem consumption: 21088868
processing file 200612, mem consumption: 21687044
processing file 20071, mem consumption: 22283780
processing file 20072, mem consumption: 22867620
processing file 20073, mem consumption: 23455460
processing file 20074, mem consumption: 24046820
processing file 20075, mem consumption: 24637636
processing file 20076, mem consumption: 25227972
processing file 20077, mem consumption: 25824164
processing file 20078, mem consumption: 26407716
processing file 20079, mem consumption: 26989028
processing file 200710, mem consumption: 27576484
processing file 200711, mem consumption: 28168964
processing file 200712, mem consumption: 28763460
processing file 20081, mem consumption: 29356004
processing file 20082, mem consumption: 29942180
processing file 20083, mem consumption: 30531652
processing file 20084, mem consumption: 31126340
processing file 20085, mem consumption: 31719620
processing file 20086, mem consumption: 32315524
processing file 20087, mem consumption: 32914020
processing file 20088, mem consumption: 33504260
processing file 20089, mem consumption: 34102564
processing file 200810, mem consumption: 34701604
processing file 200811, mem consumption: 35301412
processing file 200812, mem consumption: 35902756
processing file 20091, mem consumption: 36502340
processing file 20092, mem consumption: 37096804
processing file 20093, mem consumption: 37688772
processing file 20094, mem consumption: 38284548
processing file 20095, mem consumption: 38877668
processing file 20096, mem consumption: 39473988
processing file 20097, mem consumption: 40075012
processing file 20098, mem consumption: 40662628
processing file 20099, mem consumption: 41250628
processing file 200910, mem consumption: 41839940
processing file 200911, mem consumption: 42431044
processing file 200912, mem consumption: 43020996
processing file 20101, mem consumption: 43606916
processing file 20102, mem consumption: 44185284
processing file 20103, mem consumption: 44765860
processing file 20104, mem consumption: 45350116
processing file 20105, mem consumption: 45937284
processing file 20106, mem consumption: 46524804
processing file 20107, mem consumption: 47114468
processing file 20108, mem consumption: 47692004
processing file 20109, mem consumption: 48274916
processing file 201010, mem consumption: 48860292
processing file 201011, mem consumption: 49548900
processing file 201012, mem consumption: 50240324
processing file 20111, mem consumption: 51456484
processing file 20112, mem consumption: 52133284
processing file 20113, mem consumption: 52818372
processing file 20114, mem consumption: 53505732
processing file 20115, mem consumption: 54193348
processing file 20116, mem consumption: 54885732
processing file 20117, mem consumption: 56134852
processing file 20118, mem consumption: 56827652
processing file 20119, mem consumption: 57524228
processing file 201110, mem consumption: 58222564
processing file 201111, mem consumption: 58923012
processing file 201112, mem consumption: 59624516
processing file 20121, mem consumption: 60857348
processing file 20122, mem consumption: 61544452
processing file 20123, mem consumption: 62236516
processing file 20124, mem consumption: 62932132
processing file 20125, mem consumption: 63629252
processing file 20126, mem consumption: 64325508
processing file 20127, mem consumption: 65572996
processing file 20128, mem consumption: 66261796
processing file 20129, mem consumption: 66955620
processing file 201210, mem consumption: 67643652
processing file 201211, mem consumption: 68335748
processing file 201212, mem consumption: 69028644
processing file 20131, mem consumption: 70253060
processing file 20132, mem consumption: 70936292
processing file 20133, mem consumption: 71624164
processing file 20134, mem consumption: 72313732
processing file 20135, mem consumption: 73002340
processing file 20136, mem consumption: 73692132
processing file 20137, mem consumption: 74919076
processing file 20138, mem consumption: 75595780
processing file 20139, mem consumption: 76267332
processing file 201310, mem consumption: 76944932
processing file 201311, mem consumption: 77625380
processing file 201312, mem consumption: 78308900
processing file 20141, mem consumption: 79517988
processing file 20142, mem consumption: 80183940
processing file 20143, mem consumption: 80856068
processing file 20144, mem consumption: 81529892
processing file 20145, mem consumption: 82202596
processing file 20146, mem consumption: 82876100
processing file 20147, mem consumption: 84078564
processing file 20148, mem consumption: 84740036
processing file 20149, mem consumption: 85401540
processing file 201410, mem consumption: 86064676
processing file 201411, mem consumption: 86731012
processing file 201412, mem consumption: 87400068
processing file 20151, mem consumption: 88585156
processing file 20152, mem consumption: 89245284
processing file 20153, mem consumption: 89908900
processing file 20154, mem consumption: 90574116
processing file 20155, mem consumption: 91242244
processing file 20156, mem consumption: 91907332
processing file 20157, mem consumption: 93097060
processing file 20158, mem consumption: 93754916
processing file 20159, mem consumption: 94414052
processing file 201510, mem consumption: 95074052
processing file 201511, mem consumption: 95738788
processing file 201512, mem consumption: 96403940
processing file 20161, mem consumption: 97571140
processing file 20162, mem consumption: 98224676
processing file 20163, mem consumption: 98885220
processing file 20164, mem consumption: 99548516
processing file 20165, mem consumption: 100214948
processing file 20166, mem consumption: 100884068
processing file 20167, mem consumption: 102079236
processing file 20168, mem consumption: 102741124
processing file 20169, mem consumption: 103405060
processing file 201610, mem consumption: 104071428
processing file 201611, mem consumption: 104731556
processing file 201612, mem consumption: 105390948
processing file 20171, mem consumption: 106546980
processing file 20172, mem consumption: 107192612
processing file 20173, mem consumption: 107840228
processing file 20174, mem consumption: 108491428
processing file 20175, mem consumption: 109144420
processing file 20176, mem consumption: 109798212
processing file 20177, mem consumption: 110961956
processing file 20178, mem consumption: 111608132
processing file 20179, mem consumption: 112261060
processing file 201710, mem consumption: 112916420
processing file 201711, mem consumption: 113569828
processing file 201712, mem consumption: 114222564
processing file 20181, mem consumption: 115371524
processing file 20182, mem consumption: 116010436
processing file 20183, mem consumption: 116650724
processing file 20184, mem consumption: 117293412
processing file 20185, mem consumption: 117935652
processing file 20186, mem consumption: 118577380
processing file 20187, mem consumption: 119725284
processing file 20188, mem consumption: 120361444
processing file 20189, mem consumption: 121001828
processing file 201810, mem consumption: 121646756
processing file 201811, mem consumption: 122294276
processing file 201812, mem consumption: 122944420
processing file 20191, mem consumption: 124092100
processing file 20192, mem consumption: 124732964
processing file 20193, mem consumption: 125379332
processing file 20194, mem consumption: 126028452
processing file 20195, mem consumption: 126673892
processing file 20196, mem consumption: 127320068
processing file 20197, mem consumption: 128476708
processing file 20198, mem consumption: 129117796
processing file 20199, mem consumption: 129759972
processing file 201910, mem consumption: 130406820
processing file 201911, mem consumption: 131064164
processing file 201912, mem consumption: 131721476
processing file 20201, mem consumption: 132879812
processing file 20202, mem consumption: 133516900
processing file 20203, mem consumption: 134158564
processing file 20204, mem consumption: 134801252
processing file 20205, mem consumption: 135445860
processing file 20206, mem consumption: 136095076
processing file 20207, mem consumption: 137256132
processing file 20208, mem consumption: 137902692
processing file 20209, mem consumption: 138553188
processing file 202010, mem consumption: 139205636
processing file 202011, mem consumption: 139855076
processing file 202012, mem consumption: 140508644
processing file 20211, mem consumption: 141661124
processing file 20212, mem consumption: 142304388
processing file 20213, mem consumption: 142952452
processing file 20214, mem consumption: 143604164
processing file 20215, mem consumption: 144259044
processing file 20216, mem consumption: 144914180
processing file 20217, mem consumption: 146081828
processing file 20218, mem consumption: 146729540
processing file 20219, mem consumption: 147380452
processing file 202110, mem consumption: 148031588
processing file 202111, mem consumption: 148684484
processing file 202112, mem consumption: 149339684
processing file 20221, mem consumption: 150498628
processing file 20222, mem consumption: 151030980
processing file 20223, mem consumption: 151567524
processing file 20224, mem consumption: 152105028
processing file 20225, mem consumption: 152643396
processing file 20226, mem consumption: 153182948
processing file 20227, mem consumption: 154144356
processing file 20228, mem consumption: 154674948
processing file 20229, mem consumption: 155208260
processing file 202210, mem consumption: 155744196
processing file 202211, mem consumption: 156282660
processing file 202212, mem consumption: 156823108
processing file 20231, mem consumption: 157770500
processing file 20232, mem consumption: 158299876
processing file 20233, mem consumption: 158831972
processing file 20234, mem consumption: 159365060
processing file 20235, mem consumption: 159897604
processing file 20236, mem consumption: 160431460
processing file 20237, mem consumption: 161380580
processing file 20238, mem consumption: 161910404
processing file 20239, mem consumption: 162441636
processing file 202310, mem consumption: 162975524
processing file 202311, mem consumption: 163510404
processing file 202312, mem consumption: 164045860

In [10]:
# Utilizar somente colunas necessarias
df_clean = df_base[["#DATA_BASE", "CNPJ", "CONTA", "SALDO"]]
df_clean['#DATA_BASE'] = pd.to_datetime(df_clean['#DATA_BASE'], format='%Y%m')

df_clean

        #DATA_BASE      CNPJ     CONTA         SALDO
0       2004-01-01         0  10000007  2.024248e+11
1       2004-01-01         0  11000006  8.408377e+09
2       2004-01-01         0  11100009  2.096734e+09
3       2004-01-01         0  11300005  9.703718e+08
4       2004-01-01         0  11500001  5.341271e+09
...            ...       ...       ...           ...
5155727 2023-12-01  92894922  90800007  3.389927e+08
5155728 2023-12-01  92894922  90900000  2.053101e+10
5155729 2023-12-01  92894922  91000002  1.546806e+10
5155730 2023-12-01  92894922  91100005  1.546806e+10
5155731 2023-12-01  92894922  99999995  1.369247e+11

[5155732 rows x 4 columns]

In [12]:
conta = 39999993
saldo_minimo = 1_000_000_000_000.00
df_clean[(df_clean["CONTA"] == conta)]

        #DATA_BASE      CNPJ     CONTA         SALDO
80      2004-01-01         0  39999993  2.627288e+12
226     2004-01-01       208  39999993  8.749477e+09
366     2004-01-01     86413  39999993  5.930489e+09
472     2004-01-01    183938  39999993  1.936830e+09
566     2004-01-01    253448  39999993  3.522915e+08
...            ...       ...       ...           ...
5155338 2023-12-01  91884981  39999993  9.690543e+10
5155436 2023-12-01  92702067  39999993  3.931151e+11
5155533 2023-12-01  92816560  39999993  5.338664e+10
5155609 2023-12-01  92874270  39999993  5.985673e+10
5155691 2023-12-01  92894922  39999993  1.369247e+11

[51207 rows x 4 columns]

In [26]:
# Filtro por conta e saldo acima de threshold
df_filtrado = df_clean[(df_clean["CONTA"] == conta) & (df_clean["SALDO"] >= saldo_minimo)]
df_filtrado = df_filtrado[df_filtrado["CNPJ"] == 0]
df_filtrado = df_filtrado[df_filtrado["#DATA_BASE"].dt.year == 2023]
df_filtrado

        #DATA_BASE  CNPJ     CONTA         SALDO
4930388 2023-01-01     0  39999993  1.096066e+13
4946931 2023-02-01     0  39999993  1.107454e+13
4963560 2023-03-01     0  39999993  1.100273e+13
4980219 2023-04-01     0  39999993  1.101984e+13
4996860 2023-05-01     0  39999993  1.119740e+13
5013543 2023-06-01     0  39999993  1.108226e+13
5030266 2023-06-01     0  39999993  1.107755e+13
5043203 2023-07-01     0  39999993  1.144285e+13
5059760 2023-08-01     0  39999993  1.128933e+13
5076361 2023-09-01     0  39999993  1.169860e+13
5093045 2023-10-01     0  39999993  1.166450e+13
5109760 2023-11-01     0  39999993  1.174483e+13
5126493 2023-12-01     0  39999993  1.146402e+13
5143096 2023-12-01     0  39999993  1.146174e+13